breakpoint to center content
gurusorocaba/gurusorocaba.github.io pull request #12
Opened 2016-12-19 17:24 UTC by ptcmariano

In order to increase readability on mobile devices, a breakpoint has been created.

Can be tested in [http://paulomariano.eti.br/guru/index.html](http://paulomariano.eti.br/guru/index.html)

2016-12-20 14:48 UTC, lucasrenan requested changes

2016-12-20 14:48 UTC, lucasrenan commented on css/style.css
> +}
💅 please add a blank new line at end of file :)

2016-12-20 22:36 UTC, ptcmariano commented
ok
done

2016-12-21 09:25 UTC, lucasrenan approved these changes

2016-12-21 09:26 UTC, merged

2016-12-21 09:26 UTC, lucasrenan commented
@ptcmariano thank for you contribution <3