Improving English translation
gurusorocaba/gurusorocaba.github.io pull request #9
Opened 2016-10-22 21:03 UTC by lirielm

2016-10-22 21:15 UTC, hugonomura requested changes

2016-10-22 21:15 UTC, hugonomura commented on en.html
> +            <strong>Ruby</strong> is a dynamic, open-source programming language focused on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.
please, keep the text in lower case. this is the pattern in the text. :)

2016-10-22 21:15 UTC, hugonomura commented on en.html
> +            <strong>Ruby on Rails</strong> is a web development framework(free and open-source), optimized to increase the programmers' productivity and enjoyment while coding. It allows you to write
please, keep the text in lower case. this is the pattern in the text. :)

2016-10-23 12:07 UTC, lirielm commented on en.html
> +            <strong>Ruby</strong> is a dynamic, open-source programming language focused on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.
I'll change it, but, it is not grammatically correct then :)

2016-10-23 12:08 UTC, lirielm commented on en.html
> +            <strong>Ruby on Rails</strong> is a web development framework(free and open-source), optimized to increase the programmers' productivity and enjoyment while coding. It allows you to write
I'll change it, but, it is not grammatically correct then :)

2016-10-24 01:07 UTC, hugonomura commented on en.html
> +            <strong>Ruby</strong> is a dynamic, open-source programming language focused on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.
Yeah, it is strange, but the pt-br page follow this pattern too.

2016-10-24 01:08 UTC, hugonomura commented
hey @lucasrenan take a look in this PR

2016-10-24 21:44 UTC, lucasrenan commented on en.html
> +            <strong>Ruby</strong> is a dynamic, open-source programming language focused on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.
it's more about typographic than grammar :D

2016-10-24 21:45 UTC, lucasrenan commented
@lirielm thanks for your contribution!

@hugonomura thanks for review it.

2016-10-24 21:45 UTC, merged